import Image from 'next/image';
import '../global.css';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { LanguageSwitcher } from '../../components/language-switcher';

export const metadata = {
  title: 'Welcome to apps/gosi',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <NextIntlClientProvider messages={messages}>
        <body>
          <header className="bg-white shadow-md">
            <div className="container mx-auto flex items-center justify-between py-4">
              <div className="flex items-center">
                <Image
                  src="https://gosivvwebapp-as.azurewebsites.net/static/media/gosi_logo.f0003330.svg"
                  alt="Logo"
                  className="me-4 h-12"
                  width={300}
                  height={117}
                />
              </div>
              <div>
                <LanguageSwitcher locale={locale} />
              </div>
            </div>
          </header>

          {children}

          <footer className="mt-8 bg-white shadow-md">
            <div className="container mx-auto flex items-center justify-between py-4">
              <div>
                <p className="text-sm text-gray-600">
                  جميع الحقوق محفوظة © 2024
                </p>
              </div>
              <div className="flex items-center">
                <span className="me-2 text-sm text-gray-600">Powered by</span>
                <Image
                  src="https://gosivvwebapp-as.azurewebsites.net/static/media/masdr-logo.80dd4da7.png"
                  alt="Powered by Logo"
                  className="h-6"
                  width={57}
                  height={57}
                />
              </div>
            </div>
          </footer>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
