import './global.css';

export const metadata = {
  title: 'Welcome to moi',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          className="bg-green-600
        text-center text-white p-7"
        >
          <h1>MOI App Header</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
